### ISSUE TITLE
Issues in Teachers list view

### ISSUE THREAD

**Issue by ssudaraka** [ssudaraka/sep#36]
![teachers_view](https://cloud.githubusercontent.com/assets/7452912/10657806/1dc67976-78ae-11e5-8f78-f9f45ca7728d.png)

This just displays the values from database. We need to show Male if database value is 'm' and etc. :)
Also, disable data table sorting on columns where it is not needed.

**Comment by udarapathmin** [comment]
@arunthms01  will work on that

**Comment by arunthms01** [comment]
fixed :+1:
